language: ruby
bundler_args: --without development
script: "bundle exec rake spec"
notifications:
  email: false
notifications:
  irc: "irc.freenode.org#arbousier"
rvm:
  - 1.9.3
  - rbx-19mode
  - 1.9.2

